from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from tables import Profession

from tables import Question, Request, Answer, QuestionAnswer, RequestAnswer

professions = [
    'Повар',
    'Клоун',
    'Учитель',
    'Сварщик',
    'Альпинист',
    'Сисадмин',
    'Продавец',
    'Формашлеп',
    'Юрист',
    'Уборщик',
    'Архитектор',
    'Строитель',
    'Менеджер по продажам',
    'HR',
    'Бэкенд разработчик',
    'Дизайнер',
    'Тестировщик',
    'Data scientist',
]


def insert_profession(name, session):
    if session.query(Profession).filter_by(name=name).first() is None:
        request = Profession(name=name)
        session.add(request)
        session.commit()


def get_profession(name, session):
    return session.query(Profession).filter_by(name=name).first()


def get_question(text, session):
    return session.query(Question).filter_by(text=text).first()


def get_answer(text, session):
    return session.query(Answer).filter_by(text=text).first()


def get_question_answer(question_id, answer_id, session):
    return session.query(QuestionAnswer).filter_by(question_id=question_id, answer_id=answer_id).first()


def set_profession_question_request(proff_id, question_id, session, total_requests):
    request = session.query(Request).filter_by(profession_id=proff_id, question_id=question_id).first()
    if request is None:
        request = Request(profession_id=proff_id, question_id=question_id, count=total_requests)
    else:
        request.count = total_requests
    session.add(request)
    session.commit()
    return request


def set_profession_question_request_answer_request(proff_id, question_answer_id, count, session):
    request_answer = session.query(RequestAnswer).filter_by(profession_id=proff_id,
                                                            question_answer_id=question_answer_id).first()
    if request_answer is None:
        request_answer = RequestAnswer(profession_id=proff_id, question_answer_id=question_answer_id, count=count)
    else:
        request_answer.count = count
    session.add(request_answer)
    session.commit()
    return request_answer


def insert_profession_answers(name, question_text, answers_map, session):
    proff_id = get_profession(name, session).id
    question_id = get_question(question_text, session).id
    total_requests = sum(count for answer, count in answers_map)

    set_profession_question_request(proff_id, question_id, session, total_requests)
    for answer_text, count in answers_map:
        answer = get_answer(answer_text, session)
        qa = get_question_answer(question_id, answer.id, session)
        set_profession_question_request_answer_request(proff_id, qa.id, count, session)


def main():
    engine = create_engine('sqlite:///../db.db')
    Session = sessionmaker(bind=engine)
    session = Session()

    for p in professions:
        insert_profession(p, session)

    insert_profession_answers('Повар', 'Вы работаете в офисе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Повар', 'У вас опасная профессия?', [('Да', 40), ('Нет', 20), ('Не совсем', 40)], session)
    insert_profession_answers('Повар', 'Вы часто бываете в командировках?', [('Да', 1), ('Нет', 98), ('Не совсем', 1)], session)
    insert_profession_answers('Повар', 'Вы любите готовить?', [('Да', 90), ('Нет', 1), ('Не совсем', 9)], session)
    insert_profession_answers('Повар', 'Вы пользуетесь компьютером по работе?', [('Да', 1), ('Нет', 90), ('Не совсем', 8)], session)
    insert_profession_answers('Повар', 'Вы перфекционист?', [('Да', 50), ('Нет', 10), ('Не совсем', 40)], session)
    insert_profession_answers('Повар', 'Вы участвуете в хакатоне?', [('Да', 0), ('Нет', 100), ('Не совсем', 0)], session)
    insert_profession_answers('Повар', 'Вы знаете много людей?', [('Да', 50), ('Нет', 10), ('Не совсем', 40)], session)
    insert_profession_answers('Повар', 'Вы общительный?', [('Да', 30), ('Нет', 40), ('Не совсем', 40)], session)
    insert_profession_answers('Повар', 'Вы работаете в цирке', [('Да', 1), ('Нет', 94), ('Не совсем', 5)], session)
    insert_profession_answers('Повар', 'Вы рисуете?', [('Да', 0), ('Нет', 90), ('Не совсем', 10)], session)
    insert_profession_answers('Повар', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Повар', 'Придумываете что-то новое?', [('Да', 70), ('Нет', 20), ('Не совсем', 10)], session)
    insert_profession_answers('Повар', 'Вы работаете с документами?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Повар', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы работаете в офисе?', [('Да', 0), ('Нет', 100), ('Не совсем', 0)], session)
    insert_profession_answers('Клоун', 'У вас опасная профессия?', [('Да', 0), ('Нет', 90), ('Не совсем', 10)], session)
    insert_profession_answers('Клоун', 'Вы часто бываете в командировках?', [('Да', 45), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы пользуетесь компьютером по работе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы перфекционист?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы участвуете в хакатоне?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы знаете много людей?', [('Да', 80), ('Нет', 10), ('Не совсем', 10)], session)
    insert_profession_answers('Клоун', 'Вы общительный?', [('Да', 60), ('Нет', 20), ('Не совсем', 20)], session)
    insert_profession_answers('Клоун', 'Вы работаете в цирке', [('Да', 95), ('Нет', 1), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы работаете с документами?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Клоун', 'Вы работаете в школе?', [('Да', 1), ('Нет', 99), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы работаете в офисе?', [('Да', 5), ('Нет', 5), ('Не совсем', 85)], session)
    insert_profession_answers('Учитель', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы любите готовить?', [('Да', 45), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы пользуетесь компьютером по работе?', [('Да', 60), ('Нет', 30), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы перфекционист?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы участвуете в хакатоне?', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы знаете много людей?', [('Да', 90), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы общительный?', [('Да', 90), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы работаете с документами?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Учитель', 'Вы работаете в школе?', [('Да', 100), ('Нет', 10), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы работаете в офисе?', [('Да', 1), ('Нет', 90), ('Не совсем', 1)], session)
    insert_profession_answers('Сварщик', 'У вас опасная профессия?', [('Да', 80), ('Нет', 20), ('Не совсем', 20)], session)
    insert_profession_answers('Сварщик', 'Вы часто бываете в командировках?', [('Да', 40), ('Нет', 40), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы пользуетесь компьютером по работе?', [('Да', 1), ('Нет', 90), ('Не совсем', 1)], session)
    insert_profession_answers('Сварщик', 'Вы перфекционист?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы участвуете в хакатоне?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы знаете много людей?', [('Да', 50), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы общительный?', [('Да', 50), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы работаете в цирке', [('Да', 0), ('Нет', 90), ('Не совсем', 1)], session)
    insert_profession_answers('Сварщик', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Придумываете что-то новое?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы работаете с документами?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сварщик', 'Вы работаете в школе?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы работаете в офисе?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы часто бываете в командировках?', [('Да', 95), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы пользуетесь компьютером по работе?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы перфекционист?', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы участвуете в хакатоне?', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы знаете много людей?', [('Да', 90), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы общительный?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы работаете в цирке', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы рисуете?', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Придумываете что-то новое?', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы работаете с документами?', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Альпинист', 'Вы работаете в школе?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы работаете в офисе?', [('Да', 95), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы часто бываете в командировках?', [('Да', 20), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы пользуетесь компьютером по работе?', [('Да', 100), ('Нет', 0), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы перфекционист?', [('Да', 50), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы участвуете в хакатоне?', [('Да', 120), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы знаете много людей?', [('Да', 25), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы общительный?', [('Да', 30), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы работаете в цирке', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы рисуете?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы считаете деньги?', [('Да', 2), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Придумываете что-то новое?', [('Да', 140), ('Нет', 90), ('Не совсем', 40)], session)
    insert_profession_answers('Сисадмин', 'Вы работаете с документами?', [('Да', 15), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Сисадмин', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы работаете в офисе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'У вас опасная профессия?', [('Да', 15), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы часто бываете в командировках?', [('Да', 1), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы пользуетесь компьютером по работе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы перфекционист?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы участвуете в хакатоне?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы знаете много людей?', [('Да', 120), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы общительный?', [('Да', 120), ('Нет', 25), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы работаете в цирке', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы считаете деньги?', [('Да', 100), ('Нет', 10), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Придумываете что-то новое?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы работаете с документами?', [('Да', 20), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Продавец', 'Вы работаете в школе?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы работаете в офисе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы пользуетесь компьютером по работе?', [('Да', 100), ('Нет', 0), ('Не совсем', 0)], session)
    insert_profession_answers('Формашлеп', 'Вы перфекционист?', [('Да', 70), ('Нет', 30), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы участвуете в хакатоне?', [('Да', 100), ('Нет', 15), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы знаете много людей?', [('Да', 50), ('Нет', 50), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы общительный?', [('Да', 50), ('Нет', 50), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы работаете в цирке', [('Да', 1), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы рисуете?', [('Да', 40), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Придумываете что-то новое?', [('Да', 120), ('Нет', 25), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы работаете с документами?', [('Да', 25), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Формашлеп', 'Вы работаете в школе?', [('Да', 0), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы работаете в офисе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы пользуетесь компьютером по работе?', [('Да', 80), ('Нет', 15), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы перфекционист?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы участвуете в хакатоне?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы знаете много людей?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы общительный?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы работаете с документами?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Юрист', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы работаете в офисе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы любите готовить?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы пользуетесь компьютером по работе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы перфекционист?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы участвуете в хакатоне?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы знаете много людей?', [('Да', 70), ('Нет', 25), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы общительный?', [('Да', 70), ('Нет', 25), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы считаете деньги?', [('Да', 0), ('Нет', 95), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы работаете с документами?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Уборщик', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы работаете в офисе?', [('Да', 60), ('Нет', 35), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы часто бываете в командировках?', [('Да', 15), ('Нет', 80), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы пользуетесь компьютером по работе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы перфекционист?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы участвуете в хакатоне?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы знаете много людей?', [('Да', 60), ('Нет', 35), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы общительный?', [('Да', 60), ('Нет', 25), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы рисуете?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Придумываете что-то новое?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы работаете с документами?', [('Да', 75), ('Нет', 15), ('Не совсем', 5)], session)
    insert_profession_answers('Архитектор', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы работаете в офисе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'У вас опасная профессия?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы часто бываете в командировках?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы пользуетесь компьютером по работе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы перфекционист?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы участвуете в хакатоне?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы знаете много людей?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы общительный?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы работаете с документами?', [('Да', 55), ('Нет', 50), ('Не совсем', 5)], session)
    insert_profession_answers('Строитель', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы работаете в офисе?', [('Да', 85), ('Нет', 10), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы часто бываете в командировках?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы пользуетесь компьютером по работе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы перфекционист?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы участвуете в хакатоне?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы знаете много людей?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы общительный?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы считаете деньги?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы работаете с документами?', [('Да', 80), ('Нет', 15), ('Не совсем', 5)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы работаете в офисе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы пользуетесь компьютером по работе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы перфекционист?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы участвуете в хакатоне?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы знаете много людей?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы общительный?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы работаете с документами?', [('Да', 70), ('Нет', 25), ('Не совсем', 5)], session)
    insert_profession_answers('HR', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы работаете в офисе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы пользуетесь компьютером по работе?', [('Да', 95), ('Нет', 0), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы перфекционист?', [('Да', 80), ('Нет', 15), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы участвуете в хакатоне?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы знаете много людей?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы общительный?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы рисуете?', [('Да', 25), ('Нет', 70), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Придумываете что-то новое?', [('Да', 85), ('Нет', 10), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы работаете с документами?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы работаете в офисе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы пользуетесь компьютером по работе?', [('Да', 95), ('Нет', 0), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы перфекционист?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы участвуете в хакатоне?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы знаете много людей?', [('Да', 30), ('Нет', 65), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы общительный?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы рисуете?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Придумываете что-то новое?', [('Да', 70), ('Нет', 25), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы работаете с документами?', [('Да', 30), ('Нет', 65), ('Не совсем', 5)], session)
    insert_profession_answers('Дизайнер', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы работаете в офисе?', [('Да', 90), ('Нет', 5), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы пользуетесь компьютером по работе?', [('Да', 95), ('Нет', 0), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы перфекционист?', [('Да', 80), ('Нет', 15), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы участвуете в хакатоне?', [('Да', 30), ('Нет', 65), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы знаете много людей?', [('Да', 40), ('Нет', 55), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы общительный?', [('Да', 30), ('Нет', 65), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Придумываете что-то новое?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы работаете с документами?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Тестировщик', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы работаете в офисе?', [('Да', 95), ('Нет', 0), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'У вас опасная профессия?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы часто бываете в командировках?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы любите готовить?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы пользуетесь компьютером по работе?', [('Да', 95), ('Нет', 0), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы перфекционист?', [('Да', 50), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы участвуете в хакатоне?', [('Да', 60), ('Нет', 45), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы знаете много людей?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы общительный?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы работаете в цирке', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы рисуете?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы считаете деньги?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Придумываете что-то новое?', [('Да', 80), ('Нет', 15), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы работаете с документами?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)
    insert_profession_answers('Data scientist', 'Вы работаете в школе?', [('Да', 5), ('Нет', 90), ('Не совсем', 5)], session)


    insert_profession_answers('Повар', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Повар', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Повар', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Клоун', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Клоун', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Клоун', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Учитель', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Учитель', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Учитель', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Сварщик', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Сварщик', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Сварщик', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Альпинист', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Альпинист', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Альпинист', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Сисадмин', 'Какой язык предпочитаете?', [('java', 1), ('python', 50), ('perl', 90), ('я русский', 1)], session)
    insert_profession_answers('Сисадмин', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Сисадмин', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 1), ('Нет', 100)], session)
    insert_profession_answers('Продавец', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Продавец', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Продавец', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Формашлеп', 'Какой язык предпочитаете?', [('java', 1), ('python', 100), ('perl', 10), ('я русский', 1)], session)
    insert_profession_answers('Формашлеп', 'Что вы продаете?', [('Продукт', 1), ('Себя', 80), ('Не знаю', 30), ('Ничего', 40)], session)
    insert_profession_answers('Формашлеп', 'Вы пишете фронтенд?', [('Да', 100), ('К сожалению, да', 1), ('Что это?', 1)], session)
    insert_profession_answers('Юрист', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Юрист', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Юрист', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Уборщик', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Уборщик', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Уборщик', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Архитектор', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Архитектор', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Архитектор', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Строитель', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Строитель', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Строитель', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Менеджер по продажам', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Менеджер по продажам', 'Что вы продаете?', [('Продукт', 100), ('Себя', 20), ('Не знаю', 30), ('Ничего', 10)], session)
    insert_profession_answers('Менеджер по продажам', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('HR', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('HR', 'Что вы продаете?', [('Продукт', 40), ('Себя', 50), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('HR', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 100)], session)
    insert_profession_answers('Бэкенд разработчик', 'Какой язык предпочитаете?', [('java', 100), ('python', 20), ('perl', 1), ('я русский', 1)], session)
    insert_profession_answers('Бэкенд разработчик', 'Что вы продаете?', [('Продукт', 1), ('Себя', 1), ('Не знаю', 1), ('Ничего', 70)], session)
    insert_profession_answers('Бэкенд разработчик', 'Вы пишете фронтенд?', [('Да', 25), ('К сожалению, да', 80), ('Что это?', 10), ('Нет', 50)], session)
    insert_profession_answers('Дизайнер', 'Какой язык предпочитаете?', [('java', 1), ('python', 1), ('perl', 1), ('я русский', 97)], session)
    insert_profession_answers('Дизайнер', 'Что вы продаете?', [('Продукт', 100), ('Себя', 10), ('Не знаю', 10), ('Ничего', 10)], session)
    insert_profession_answers('Дизайнер', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 100), ('Нет', 50)], session)
    insert_profession_answers('Тестировщик', 'Какой язык предпочитаете?', [('java', 80), ('python', 10), ('perl', 1), ('я русский', 1)], session)
    insert_profession_answers('Тестировщик', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Тестировщик', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 20), ('Нет', 70)], session)
    insert_profession_answers('Data scientist', 'Какой язык предпочитаете?', [('java', 1), ('python', 100), ('perl', 1), ('я русский', 1)], session)
    insert_profession_answers('Data scientist', 'Что вы продаете?', [('Продукт', 1), ('Себя', 20), ('Не знаю', 30), ('Ничего', 70)], session)
    insert_profession_answers('Data scientist', 'Вы пишете фронтенд?', [('Да', 1), ('К сожалению, да', 1), ('Что это?', 10), ('Нет', 100)], session)

    insert_profession_answers('Строитель', 'Вы работаете с техникой?', [('Да', 100), ('Нет', 20)], session)
    insert_profession_answers('Сварщик', 'Вы работаете с техникой?', [('Да', 100), ('Нет', 20)], session)
    insert_profession_answers('Учитель', 'Вы преподаёте?', [('Да', 100), ('Нет', 1)], session)

if __name__ == '__main__':
    main()
